### PR TITLE
bootstrap project

### PR DESCRIPTION
**Pull request by zoedberg**
Re-opening another draft PR since https://github.com/RGB-WG/rgb-integration-tests/pull/1 was merged before it was ready (I've force pushed master to revert it). Please @dr-orlovsky DON'T merge or review this until I mark it as ready.

Since last PR I've:
- refactored the transfers test, now we have a much more complete test where several possible scenarios are tested using 2 wallets, 2 assets and a transfer type (that can be blinded or witness)
- improved README
- updated submodules to beta 6
 
I still need to:
- do a general code refactor/cleanup
- wait for upstream fixes and beta 8 to be released

### CODE REVIEW

**Comment by zoedberg** [comment]
I've updated this PR. Now it includes all tests that were added in separate branches (to report single issues) and it's ready to be merged.

@dr-orlovsky  please note:
- the TODO in the `accept_0conf` test, I think the commented code shows a bug on how RGB shows allocations of a 0-confirmations transfer
- the `tapret_wlt_receiving_opret` test is failing (so I've temporarily ignored it), this was working after https://github.com/RGB-WG/rgb-std/pull/256 but it now fails again, should I re-open https://github.com/RGB-WG/rgb-std/issues/246 or open a new issue?
- I've added a `mainnet_wlt_receiving_test_asset` test that shows that a mainnet wallet refuses a test asset, therefore the issue reported in telegram by memes_ceo should not be possible

**Comment by dr-orlovsky** [comment]
Thank you very much!

> the TODO in the `accept_0conf` test, I think the commented code shows a bug on how RGB shows allocations of a 0-confirmations transfer

Is it the same problem reported by Bitlight team? Anyway I think we need an issue for it

> the tapret_wlt_receiving_opret test is failing (so I've temporarily ignored it), this was working after 

Let's have a new issue

> I've added a mainnet_wlt_receiving_test_asset test that shows that a mainnet wallet refuses a test asset, therefore the issue reported in telegram by memes_ceo should not be possible

Nice to know that, thank you!

**Review by dr-orlovsky — APPROVED** [review]
ACK 132b8ba2b30ad33b823ccb0dd6164fba071971d6

**Comment by zoedberg** [comment]
> Is it the same problem reported by Bitlight team? Anyway I think we need an issue for it

Not sure which problem you are referring to. Anyway here the issue https://github.com/RGB-WG/rgb-std/issues/270

> Let's have a new issue

Ok, here it is https://github.com/RGB-WG/rgb-std/issues/271

**Pull request merged**
